const showsData = [
  {
    id: 84822,
    title: "The Precious Memory of Gogo Brothers 2",
    img: "https://occ-0-1361-988.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABcy7Are3BUAXfypd2iqXrWXo6N7LST8qn6rKtFD24lljZzDB-N3qEJjoL02E0lps2L8QXBGjv-xIKbSDT6hPX78CKSvWbB331A.jpg?r=fb3",
    vtype: "movie",
    nfid: 81662480,
    synopsis:
      "After spending his tuition to impress a crush, a young boy goes on a journey to make the money back — weathering twists and turns along the way.",
    avgrating: 0,
    year: 2022,
    runtime: 4759,
    imdbid: null,
    poster: null,
    imdbrating: null,
    top250: null,
    top250tv: null,
    clist: '"KR":"South Korea"',
    titledate: "2023-01-25",
  },
  {
    id: 84821,
    title: "Pinkfong Sing-Along Movie 2: Wonderstar Concert",
    img: "https://occ-0-1361-988.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABeGMixLB4ZT9ToC6HYgAkp9VoBxoRTfFrM49Q5rYHmUQHnShJHDCuXyVdcr6ter8_xzqUdWHsB7djv-X5WFAYa5V9VC6mxNVow.jpg?r=646",
    vtype: "movie",
    nfid: 81648577,
    synopsis:
      "Join Pinkfong, Hogi and the gang as they put together a concert showcasing their favorite songs — sing along for a super-fun learning experience!",
    avgrating: 0,
    year: 2022,
    runtime: 4255,
    imdbid: "tt23871460",
    poster: "0",
    imdbrating: 0,
    top250: null,
    top250tv: null,
    clist: '"KR":"South Korea"',
    titledate: "2023-01-25",
  },
  {
    id: 84820,
    title: "Hello Jadoo: The Secret of Jeju Island",
    img: "https://occ-0-1361-988.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABRMfomuaQkG3rcHIcUdxZjp5dO4YM33nIofyNpYOu3olrhSzv8NE_cI4XALSdrFpXRfyk_q5c_afWbolSYER0kRirEoLOkw_Ug.jpg?r=6f9",
    vtype: "movie",
    nfid: 81662481,
    synopsis:
      "After accidentally awakening a spirit that starts turning people to stone, Jadoo must find a way to save the people of Jeju Island.",
    avgrating: 0,
    year: 2022,
    runtime: 5378,
    imdbid: "tt18115222",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjcxY2I2YTYtZGY5MC00NWY4LWEzZTctMDk0ZDNjZDNjZTI1XkEyXkFqcGdeQXVyMDM1MzY1Mg@@._V1_SX300.jpg",
    imdbrating: 0,
    top250: null,
    top250tv: null,
    clist: '"KR":"South Korea"',
    titledate: "2023-01-25",
  },
  {
    id: 84819,
    title: "Love Never Lies: Poland",
    img: "https://occ-0-3946-2567.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABe_KkIDriej-L-XBH1W4GRTgYU690i_pT_CxET1ggD6feqrtQzC3ByYKFLvOj9Kr0Ut0FCgkOMBbTckjJ9tzLcC-vdr6uzmwuqyBJEikRRhGsjt-VIzMFcY7ZrJM6yI2nmQ.jpg?r=ddc",
    vtype: "series",
    nfid: 81582706,
    synopsis:
      "Six couples test their trust with an eye-scanning lie detector in this reality series where deception costs money, and the truth comes with a prize.",
    avgrating: 0,
    year: 2023,
    runtime: 0,
    imdbid: null,
    poster: null,
    imdbrating: null,
    top250: null,
    top250tv: null,
    clist:
      '"US":"United States","AU":"Australia","BR":"Brazil","HK":"Hong Kong","IN":"India","JP":"Japan","PH":"Philippines","KR":"South Korea"',
    titledate: "2023-01-25",
  },
  {
    id: 84816,
    title: "The Endless Night",
    img: "https://occ-0-3946-2567.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABW9PhYUltEu8TQ8ED-7x2_IUxIshqrda0AOv1dA832c6VnnERCRcQKE8xpNmjCiDdlb7QUvQGq6mjiZlgIP2w56mLCgKaoFsqljz6vcjn8lDitSCVIdOAYtJlCEDekQr604.jpg?r=9ac",
    vtype: "series",
    nfid: 81218409,
    synopsis:
      "When a fire kills 242 people in a nightclub, all that the victims&#39; parents can do is mourn... and fight for justice.",
    avgrating: 0,
    year: 2023,
    runtime: 0,
    imdbid: "tt0057035",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYzllYWNlYTMtYjIyOS00NGUyLWIwYWYtZGMyNzAyN2U5M2Y2XkEyXkFqcGdeQXVyODQ2MDE3NjE@._V1_SX300.jpg",
    imdbrating: 7,
    top250: null,
    top250tv: null,
    clist:
      '"AU":"Australia","BR":"Brazil","HK":"Hong Kong","IN":"India","JP":"Japan"',
    titledate: "2023-01-25",
  },
  {
    id: 84815,
    title: "Against the Ropes",
    img: "https://occ-0-3946-2567.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABc2IU0_KvvdUr7Jzom_qWuDfta5TS2j7Awt2S8JB6EsJywLxHVh2fOWxwrL5PH3akDkMafDCuXfyMxnu6Fmm1NckAAAoeIhatTUZkf4uc_arsNEnvgxAwRKwI_xYPtJpT2c.jpg?r=4d0",
    vtype: "series",
    nfid: 81434745,
    synopsis:
      "Released from prison, Ángela tries to regain the respect of her daughter, who loves lucha libre wrestling, by entering the ring as a mysterious persona.",
    avgrating: 0,
    year: 2023,
    runtime: 0,
    imdbid: "tt0312329",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjk1NWExNjctOTlmYy00ZjFlLThjN2ItN2FkMTI5YzVlZTY1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbrating: 5.3,
    top250: null,
    top250tv: null,
    clist: '"AU":"Australia"',
    titledate: "2023-01-25",
  },
  {
    id: 84812,
    title: "Bodies Bodies Bodies",
    img: "https://occ-0-1223-64.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABdi5f4yeJIXoE7N0xTQCAt6JADi9YvXfUOTOboAwsjLiva-Kb7VHJsJEfjRB1pQ43sKZ1oaq0HdgfMFHpJWWYPNQLaMZ3NicWA.jpg?r=186",
    vtype: "movie",
    nfid: 81586776,
    synopsis:
      "When a group of rich twentysomethings plan a get-together at a remote family mansion, a fun party game descends into backstabbing, duplicity and murder.",
    avgrating: 0,
    year: 2022,
    runtime: 5660,
    imdbid: "tt8110652",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYTA2ODg5ZjgtOTU2My00MzFkLWI0NzMtZmQ5MmRhMWU1NzhlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg",
    imdbrating: 6.3,
    top250: null,
    top250tv: null,
    clist:
      '"HK":"Hong Kong","IN":"India","MY":"Malaysia","PH":"Philippines","SG":"Singapore","TH":"Thailand"',
    titledate: "2023-01-25",
  },
  {
    id: 84811,
    title: "George Lopez: Why You Crying?",
    img: "https://occ-0-7126-1167.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABbMBXuGKft5gX1VqdLa1Ykh_C-i8ZZrdZl7WlU9cqYOpTIpPDkOh6B3eITvnMdNDj8iFctxLjxH2-6DIewPMB8Y5wm-JUWK2DQ.jpg?r=97e",
    vtype: "movie",
    nfid: 70037036,
    synopsis:
      "George Lopez unpacks his experiences growing up in Los Angeles in this special that tackles family dynamics, deep insecurities and many other topics.",
    avgrating: 0,
    year: 2005,
    runtime: 3590,
    imdbid: "tt6344974",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDQ1MGZiYWEtZjJiMS00NzNhLWI4MzItMWY3YmRiNGMxNzBhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNzEwMDgyNzk@._V1_SX300.jpg",
    imdbrating: 6.9,
    top250: null,
    top250tv: null,
    clist: '"CZ":"Czech Republic"',
    titledate: "2023-01-25",
  },
  {
    id: 84810,
    title: "Air Force The Movie: Danger Close",
    img: "https://occ-0-7397-2774.1.nflxso.net/dnm/api/v6/WNk1mr9x_Cd_2itp6pUM7-lXMJg/AAAABftGm_Oik_Xf2GYR6PUYK7EbmC77mtaEeTrJS7wYp0Kq_e5my74A_tO5TR-Kt12gvL1RQMfsj3hc6sZic6ivXTM67DWRODDZnQ.jpg?r=d41",
    vtype: "movie",
    nfid: 81631030,
    synopsis:
      "After a militia group shoots down a special forces aircraft, nine survivors must hold out on the ground while a rescue mission is devised.",
    avgrating: 0,
    year: 2022,
    runtime: 6203,
    imdbid: null,
    poster: null,
    imdbrating: null,
    top250: null,
    top250tv: null,
    clist:
      '"FR":"France","DE":"Germany","NL":"Netherlands","PL":"Poland","GB":"United Kingdom","AU":"Australia","BE":"Belgium","BR":"Brazil","CZ":"Czech Republic","GR":"Greece","more":"+19"',
    titledate: "2023-01-25",
  },
];

export default showsData;
